---
- name: "Duffy Inventory Filter Testing"
  hosts: localhost
  gather_facts: false
  vars_files:
   - ../linchpin_config.yml
   - ../ex_topo/duffy_topology_output.yml
  vars:
    data: '../ex_topo/duffy_3node_cluster.yml'
    schema: '../ex_schemas/schema_v2.json'
    state: present
    output:
      output:
        data:
         topology_name: "duffy_3node_cluster"
    topology_outputs_duffy: "{{ duffy_res }}"
    topology_outputs_os_server: "[]"
    topology_outputs_os_volume: "[]"
    topology_outputs_os_object: "[]"
    topology_outputs_os_heat: "[]"
    topology_outputs_os_keypair: "[]"
    topology_outputs_aws: "[]"
    topology_outputs_aws_ec2: "[]"
    topology_outputs_aws_s3: "[]"
    topology_outputs_aws_ec2_key: "[]"
    topology_outputs_aws_cfn: "[]"
    topology_outputs_gce: "[]"

  roles:
    - output_writer
