---
# This playbook provisions given topology.

- name: "including the configuration files"
  hosts: localhost
  tasks:
    - name: "Include linchpin_config"
      include_vars: "{{ item }}"
      with_first_found:
        - "../linchpin_config.yml"
        - "~/.linchpin_config.yml"
        - "/etc/linchpin/linchpin_config.yml" 
 
- name:  "schema check and Pre Provisioning Activities  on topology_file"
  hosts: localhost
  roles:
    - { role: 'common' }
 
- name:  "Provisioning resources based on resource group type"
  hosts: localhost 
  roles:
    - { role: 'openstack', when: os_res_grps | length > 0  }
    - { role: 'aws', when: aws_res_grps | length > 0 }
    - { role: 'gcloud', when: gcloud_res_grps | length > 0 }
    - { role: 'duffy', when: duffy_res_grps | length > 0}
    - { role: 'libvirt', when: libvirt_res_grps | length > 0 }
    - { role: 'rackspace', when: rax_res_grps | length > 0 }

- name: "Writing contents to file"
  hosts: localhost
  roles:
    - { role: 'output_writer'}

- name: "inventory generation role"
  hosts: localhost
  roles:
    - { role: 'inventory_gen', when: state == 'present' }
