---
# This playbook provisions given topology. 
- name:  "schema check and Pre Provisioning Activities  on topology_file"
  hosts: localhost
  roles:
    - { role: 'common' }
 
- name:  "Provisioning resources based on resource group type"
  hosts: localhost 
  roles:
    - { role: 'openstack', os_res_grps: "{{ os_res_grps }}" }
    - { role: 'aws', aws_res_grps: "{{ aws_res_grps  }}" }
    - { role: 'gcloud', gce_res_grps: "{{ gcloud_res_grps }}" }
    - { role: 'duffy', duffy_res_grps: "{{ duffy_res_grps }}" }

- name: "Writing contents to file"
  hosts: localhost
  roles:
    - { role: 'output_writer', topology_outputs: "{{ topology_outputs }}" }
