sudo: false

language: python

python:
  - "2.7"
#  - "3.6"

cache: pip

install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install .
  - pip install .[tests]

script:
  - flake8 --exclude=\.eggs,tests,docs --ignore=E124,E303 --max-line-length 80 .
  - nosetests -s linchpin/tests/*
