sudo: false

language: python

python:
  - "2.7"
  - "3.6"

cache: pip

install:
  - pip install -U pip
  - pip install .
  - pip install .[tests]

script:
  - 
  - nosetests -s linchpin/tests/{cli,api}/*
