---

- include_vars: "{{ inventory_layout_file }}"
  when: state == "present"

- name: "Updating topology_outputs"
  set_fact:
    topology_outputs:
      os_server_res: "{{ topology_outputs_os_server }}"
      os_volume_res: "{{ topology_outputs_os_volume }}"
      os_obj_res: "{{ topology_outputs_os_object }}"
      os_heat_res: "{{ topology_outputs_os_heat }}"
      aws_ec2_res: "{{ topology_outputs_aws }}"
      gcloud_gce_res: "{{ topology_outputs_gce }}"
      duffy_res: "{{ topology_outputs_duffy }}"

- name: "create output directories"
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ outputfolder_path | default( outputfolder_path+'/' ) }}"
    - "{{ inventoryfolder_path | default( inventoryfolder_path+'/' ) }}"

- name: "DEBUG:: topology_outputs"
  debug:
    msg: "{{ topology_outputs }}"

- name: "DEBUG:: inventory_layout"
  debug:
    msg: "{{ inventory_layout }}"
  when: state == "present"

- name: "generate outputs"
  template:
    src: "../templates/output_formatter.j2"
    dest: "{{ topology_output_file | default( outputfolder_path+'/'+output.output.data.topology_name+'.output' ) }}"
  when: state == "present"

# include inventory generation files here
- include: "{{ item }}"
  with_items:
    - "{{ inventory_playbooks }}"
  when: state == "present"
