- name: "os_server: wait and update outputs using jobids "
  include: update_os_server_outputs.yml
  when: async == true

- name: "os_obj: wait and update outputs using jobids "
  include: update_os_obj_outputs.yml
  when: async == true

- name: "os_volume: wait and update outputs using jobids "
  include: update_os_volume_outputs.yml
  when: async == true

- name: "os_heat: wait and update outputs using jobids "
  include: update_os_heat_outputs.yml
  when: async == true

