#- name: 'check on fire and forget task os_server_res'
#  async_status_custom:
#    jid: "{{ item['ansible_job_id'] }}"
#    module_name: "os_server"
#  register: job_result
#  until: job_result.finished
#  retries: 30
#  with_items: "{{ topology_outputs['os_server_res'] }}"
#
#

- name: "register var for async_outputs_os_server"
  set_fact:
    async_outputs_os_server: [] 
  
- name: "Wait on jobs"
  include: wait_on_os_server.yml
  vars:
    os_server_group: "{{ item }}"
  with_items:  "{{ topology_outputs['os_server_res'] }}"
