- name: "register resource count"
  shell: python -c "print [x for x in range( 0, {{ res_def['count'] | default(1) }} )]"
  register: res_count

- name: "does node already exist"
  virt:
    name: "{{ libvirt_resource_name }}_{{ nodeinfo[1] }}"
    command: status
    uri: "{{ nodeinfo[0]['uri'] | default('qemu:///system') }}"
  with_nested:
    - ["{{ res_def }}"]
    - "{{ res_count.stdout }}"
  ignore_errors: yes
  loop_control:
    loop_var: nodeinfo
  register: node_exists

- name: set empty local_image_path
  set_fact:
    local_image_path: ''

- name: set empty img_src_ext
  set_fact:
    img_src_ext: ''

- name: "copy image_src"
  include: copy_image_src.yml
  when: node_exists['failed'] is defined

- name: set qemu_path
  set_fact:
      qemu_path: "{{ (ansible_distribution in ['CentOS','RedHat']) | ternary('/usr/libexec/', '/usr/bin/') }}"

- name: "define node"
  virt:
    name: "{{ libvirt_resource_name }}_{{ definition[1] }}"
    command: define
    xml: "{{ lookup('template', 'libvirt_node.xml.j2') }}"
    uri: "{{ definition[0]['uri'] | default('qemu:///system') }}"
  with_nested:
    - ["{{ res_def }}"]
    - "{{ res_count.stdout }}"
    - ["{{ local_image_path }}"]
    - ["{{ img_src_ext }}"]
  loop_control:
    loop_var: definition
  when:  node_exists['failed'] is defined

- name: "start relevant networks"
  virt_net:
    state: active
    name: "{{ net_item['name'] }}"
  with_items:
    - "{{ res_def['networks'] }}"
  loop_control:
    loop_var: net_item

- name: "start node"
  virt:
    name: "{{ libvirt_resource_name }}_{{ instance[1] }}"
    state: running
    uri: "{{ instance[0]['uri'] | default('qemu:///system') }}"
  with_nested:
    - ["{{ res_def }}"]
    - "{{ res_count.stdout }}"
    - ["{{ local_image_path }}"]
    - ["{{ img_src_ext }}"]
  loop_control:
    loop_var: instance
  when: not async

- name: mac_and_ip | extract mac address
  shell: >
    virsh -c {{ node[0]['uri']| default('qemu:///system') }} dumpxml {{ libvirt_resource_name }}_{{ node[1] }}
    | grep 'mac address'
    | cut -f 2 -d "'"
  with_nested:
    - ["{{ res_def }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: node
  register: extract_mac_address_result

#- name: extract_mac_address_result
#  debug:
#    var: extract_mac_address_result.results[0].stdout

- name: mac_and_ip | wait for dhcp ip address
  shell: |
    until arp -an | grep -q -F {{ extract_mac_address_result.results[mac].stdout }}; do
      sleep 1
    done
    arp -an | grep -F {{ extract_mac_address_result.results[mac].stdout }} | cut -f 2 -d "(" | cut -f 1 -d ")"
  with_items:
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: mac
  register: extract_ip_address_result

- name: "dump node data"
  virt:
    name: "{{ libvirt_resource_name }}_{{ data[1] }}"
    command: get_xml
    uri: "{{ data[0]['uri'] | default('qemu:///system') }}"
  with_nested:
    - ["{{ res_def }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: data
  when: not async
  register: node_data

- name: "Append ip_addresses and node_data to topology_outputs_libvirt_nodes"
  set_fact:
    topology_outputs_libvirt_nodes: "{{ topology_outputs_libvirt_nodes + [extract_ip_address_result.results[xml_item].stdout] }}"
  with_items:
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: xml_item
  when: not async
