- name: "DEBUG:: teardown of resource group {{ res_grp }}"
  debug:
    msg: "The current server obj is {{ res_grp }} "

- name: "Including credentials of current resource {{ res_grp['resource_group_name'] }} "
  include_vars: "roles/aws/vars/{{ res_grp['assoc_creds'] }}.yml"
  no_log: true 

- name: "Parsing topology output file "
  output_parser:
    output_file: "{{ topo_output_file }}"
  register: topo_output

- name: "teardown AWS ec2 resources"
  include: teardown_res_defs.yml
  when: state == "absent"
