- name: provisioning the os volume resource type
  os_volume:
    auth:
      auth_url: "{{ endpoint }}" 
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project }}" 
    state: "{{ state }}"
    size: "{{ res_def['size'] }}"
    display_name: "{{ res_def['res_name'] }}"
