- name: "Provisioning  keypair"
  os_keypair:
    auth:
      auth_url: "{{ endpoint }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project }}"
    name: "{{ res_def['res_name']  }}"
    state: "{{ state }}"
    wait: "yes"
  register: res_def_output 


- name: "Generate keyfile "
  copy: 
    content: "{{ res_def_output['key']['private_key'] }}"
    dest: "{{ keystore_path }}/{{ res_def['res_name'] }}.key"
  when: state=="present" and res_def_output['changed'] == true

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_os_keypair: "{{ topology_outputs_os_keypair + [res_def_output] }}"
  when: res_def_output.changed == true and state == "present"
