---
- name: "Get the resource name"
  set_fact:
    rsrc_name: "{{ res_def['res_name'] | default(res_def['name']) }}"

- name: "Create name using uhash value"
  set_fact:
    os_resource_name: "{{ rsrc_name + '-' + uhash + '-' }}"

- name: "provision/teardown resources of type {{ res_def['res_type'] | default(res_def['type']) }}"
  include: "provision_{{ res_def['res_type'] | default(res_def['type']) }}.yml"

