---
- name: "Unset the authvar from previous run"
  set_fact:
    auth_var: ""

- name: "set default_cred_profile when res_grp[credentials] is undefined"
  set_fact:
    cred_profile: 'default'
  when: res_grp['credentials'] is not defined

- name: "set default_cred_profile when res_grp[credentials] is undefined"
  set_fact:
    cred_name: 'default'
  when: res_grp['credentials'] is not defined

- name: "set cred_profile when res_grp[credentials] is defined"
  set_fact:
    cred_profile: "{{ res_grp['credentials']['profile'] }}"
  when: res_grp['credentials'] is defined

- name: "set default_cred_profile when res_grp[credentials] is defined"
  set_fact:
    cred_name: "{{ res_grp['credentials']['name'] }}"
  when: res_grp['credentials'] is defined

- name: "Get creds from auth driver"
  auth_driver:
    filename: "{{ cred_name }}" # don't include the .yaml
    cred_type: "openstack"
    cred_path: "{{ creds_path | default('~/.config/openstack/') }}"
    driver: "file"
  register: auth_var
  ignore_errors: true

- name: "set auth_var"
  set_fact:
    auth_var: "{{ auth_var['output']['clouds'][cred_profile]['auth'] }}"
  ignore_errors: true

- name: "provisioning resource definitions of current group"
  include: provision_res_defs.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  with_nested:
    - "{{ res_grp['res_defs'] | default(res_grp['resource_definitions']) }}"
    - ["{{ res_grp['resource_group_name'] }}"]
  loop_control:
    loop_var: res_item
