---
# This playbook will initiate provisioning for the duffy resources groups.
- name: "DEBUG:: Duffy resource group list"
  debug:
    msg: "Currently provisioning the resources under list duffy_res_grps {{ duffy_res_grps }}"

- name: "declaring output vars"
  set_fact:
    topology_outputs_duffy: []

- name: "Initiating  Provisioning of resources duffy resource group"
  include: provision_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ duffy_res_grps }}"
