---
# tasks file for libvirt
- name: "DEBUG: Libvirt resource group list"
  debug:
    msg: "Currently Provisioning/Deprovisioning the resources under list libvirt_res_grps {{ libvirt_res_grps }}"
- name: "debug task libvirt resources are"
  debug:
    var: "{{ item }}"
  with_items:
    - "{{ libvirt_res_grps }}"

- name: "declaring output vars"
  set_fact:
    topology_outputs_libvirt: []

- name: "Initiating  Provisioning/Deprovioning of resources Openstack resource group"
  include: provision_resource_group.yml res_grp={{ item }} 
  with_items:
    - "{{ libvirt_res_grps }}"
  register: resource_grps_output
